Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
    # Mysql
    config.vm.define "sql01" do |sql01|
        sql01.vm.box = "eurolinux-vagrant/centos-stream-9"
        sql01.vm.hostname = "sql01"
        sql01.vm.network "private_network", ip: "192.168.56.23"
        sql01.vm.provider "virtualbox" do |vb|
            vb.memory = "600"
        end
        sql01.vm.provision "shell", path: "sql.sh"  

    end

    # MemCache
    config.vm.define "mc01" do |mc01|
        mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
        mc01.vm.hostname = "mc01"
        mc01.vm.network "private_network", ip: "192.168.56.24"
        mc01.vm.provider "virtualbox" do |vb|
            vb.memory = "600"
        end
        mc01.vm.provision "shell", path: "mc.sh"  
    end
    # RabbitMQ
    config.vm.define "rmq01" do |rmq01|
        rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
        rmq01.vm.hostname = "rmq01"
        rmq01.vm.network "private_network", ip: "192.168.56.25"
        rmq01.vm.provider "virtualbox" do |vb|
            vb.memory = 600
        end
        rmq01.vm.provision "shell", path: "rmq.sh"  
    end
    # tomcat
    config.vm.define "app01" do |app01|
        app01.vm.box = "eurolinux-vagrant/centos-stream-9"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.56.26"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = 800
        end
        app01.vm.provision "shell", path: "app.sh"  
    end
    # nginx
    config.vm.define "web01" do |web01|
        web01.vm.box = "ubuntu/jammy64"
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.56.27"
        web01.vm.provider "virtualbox" do |vb|
            vb.gui = true
            vb.memory = "800"
        end
        web01.vm.provision "shell", path: "web.sh"  
    end
end